### ISSUE TITLE
Big problem with gulp-sass

### ISSUE THREAD

**Issue by drazik** [floridoo/gulp-sourcemaps#114]
Hello,

I am aware that some other issues relative to gulp-sass have already been posted. But I was doing some test and figured out that there is a very big problem when using gulp-sourcemaps with gulp-sass.

Beginning with a very simple example, we have the following gulp task : 

```javascript
gulp.task('styles', function() {
    gulp.src('src/public/style/scss/global.scss')
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(sass({
            outputStyle: 'compressed'
        }))
        .pipe(sourcemaps.write())
        .pipe(gulp.dest('build/public/css'));
});
```

And here is `global.scss` : 

```css
.test {
    color: red;
    text-align: center;
}
```

The result is the following : 

```css
.test{color:red;text-align:center}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImdsb2JhbC5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLEFBQ0ksQUFBTyxBQUNQLEFBQVkiLCJmaWxlIjoiZ2xvYmFsLmNzcyJ9 */
```

But when I open my devtools (Firefox or Chrome), it tells me that .test is located in ```global.scss``` (this is right) at line 3 (this is wrong, it's at line 1).

I wanted to go further, just to see if the problem persists. I tried with this `global.scss` : 

```css
@import 'file1';
@import 'file2';
```

Here is `file1.scss` : 

```css
.test1 {
    color: green;
}
```

And here is `file2.scss` : 

```css
.test2 {
    color: white;
}
```

The result of the gulp task is the following : 

```css
.test1{color:green}.test2{color:white}
/*# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJzb3VyY2VzIjpbImZpbGUxLnNjc3MiLCJmaWxlMi5zY3NzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLEFBQ0ksQUFBTyxBQ0RYLEFBQ0ksQUFBTyIsImZpbGUiOiJnbG9iYWwuY3NzIn0= */
```

This time, devtools tell me that both `.test1` and `.test2` and located at `file2.scss` line 2, which is incorrect for both since `.test1` is located at `file1.scss` line 1 and `.test2` is located at `file2.scss` line 1.

I'm using gulp@3.8.11, gulp-sass@1.3.3 and gulp-sourcemaps@1.5.2. Does somebody have an idea of what's wrong ?

Thank you.
