### ISSUE TITLE
[CSS] Attribute Selectors don't get mapped (dependency problem)

### ISSUE THREAD

**Issue by maximedaoust** [floridoo/gulp-sourcemaps#219]
CSS2 Attribute Selector don't get mapped if they are used alone or first in multiple selection.

In _page.scss file, I wrote the following styles :

``` scss
[data-page].default {
    background: blue;
}

.default[data-page] {
    background: red;
}

[data-page],
.default {
    background: orange;
}

.default,
[data-page] {
    background: green;
}
```

 And here's the result in Chrome (same result in Firefox).
As you can see the [data-page] selector don't get mapped to _page.scss.

![attribute-selector](https://cloud.githubusercontent.com/assets/8137924/17639926/bb772a1c-60c5-11e6-8b56-4ca709587541.jpg)
